### ISSUE TITLE
Broken dependencies

### ISSUE THREAD

**Issue by goatchurchprime** [BastiaanOlij/godot_vr_climbing_demo#1]
![image](https://user-images.githubusercontent.com/677254/141799336-90a322df-ce6a-4a81-b102-aeb8495cad19.png)

**Comment by BastiaanOlij** [comment]
UGH! Must have copied the wrong gitignore that is excluding obj files because they are compiled objects... let me fix that up :)

**Comment by BastiaanOlij** [comment]
Should be fixed now, just pull master :)
