### ISSUE TITLE
Does this project run locally on a Quest2?

### ISSUE THREAD

**Issue by Eisenspalter** [BastiaanOlij/godot_vr_climbing_demo#2]
Great video and project. I try to run this project locally on my Quest2. So I installed and run the Android Studio (SDK), create a keystore and create an APK. I installed the APK with Sidequest on my Quest2. But if I start the app the app didn't start. I see only three dots and nothing happen. Can this project in principle run locally on a Quest2? Or do I have missed to set some VR or Quest2 options during the build? There are some videos on youtube for the Quest1 but it seems they are outdated. Is there some new stuff? Thx for help.

**Comment by BastiaanOlij** [comment]
Heya, in theory it should work on the quest 2 just fine with the latest version of the OpenXR plugin. I didn't do much work around making sure its optimised. I've heard others mention about their projects not loading properly on a Quest 2 but that usually turns out to be because they forgot to call initialise on the plugin. That should be happening here though.

**Comment by Eisenspalter** [comment]
I can't get Godot to run on Quest2. Is there a new video or a step by step document for Quest2 with the current Godot version? A friend of mine also failed because of VR Godot.

**Comment by BastiaanOlij** [comment]
Try and see if the new release of the plugin works for you: https://github.com/GodotVR/godot_openxr/releases/tag/1.1.1
So far a number of people have reported issues, but I also know various Quest 2 users that are able to use this just fine. So far I'm in the dark as to why it doesn't work for everyone but I'm hoping it is just an issue with the previous version of the plugin.

**Comment by chrisskeddy** [comment]
![Capture](https://user-images.githubusercontent.com/11667734/149363844-f3518b07-a8cf-4a68-99c4-d29a1c871d4d.PNG)
I saw your video and decided to try it out. I tried just changing my android export to OpenXR instead of Regular. Not sure if more steps are required. I'm also using Oculus Quest 2

**Comment by BastiaanOlij** [comment]
Ah! that makes sense. It looks like the .so files are being filtered out so the plugin is incomplete. Let me rectify that (and update this repo to include the 1.1.1 version of the add on).

**Comment by BastiaanOlij** [comment]
Ok all fixed up! if you pull a new version it should have the new plugin and contain the missing files!

**Comment by chrisskeddy** [comment]
I did a pull and the loading(3 dots)/blank screen is no longer a problem. Likely safe to close this issue.

**Comment by BastiaanOlij** [comment]
Thanks for letting me know, glad we found the real cause in the end :)
